### ISSUE TITLE
请问是否支持STS授权策略配置

### ISSUE THREAD

**Issue by btfak** [MieYua/Aliyun-OSS-Go-SDK#4]
http://docs.aliyun.com/#/pub/oss/product-documentation/acl&policy-configure

**Comment by MieYua** [comment]
抱歉，暂时不支持，这个是新增功能，感觉上个月都没有的。

**Comment by btfak** [comment]
近期有支持计划吗？

**Comment by MieYua** [comment]
已支持，本地测试基本操作没问题，可能会有bug（写了一天，现在不做这个了，没精力全部测试），欢迎报告bug。

**Comment by btfak** [comment]
感谢！
